#!/bin/bash
#SBATCH --time=%(wall_time_hrs)02d:00:00 # walltime, abbreviated by -t
#SBATCH --ntasks=%(np)d   # number of MPI tasks, abbreviated by -n
#SBATCH --nodes=%(nodes)d     # number of cluster nodes, abbreviated by -N
#SBATCH --nodelist=ember-gg[01-12] # only use GG nodes
#SBATCH --job-name=WRFX  # job name

# set data and working directories
export WORKDIR=%(cwd)s 
cd $WORKDIR

source ~/.wrf_arm

time mpirun -np $SLURM_NTASKS -x UCX_NET_DEVICES=mlx5_2:1 --mca pml ucx --mca btl self ./wrf.exe
