#!/bin/bash
#SBATCH --time=%(wall_time_hrs)02d:00:00 # walltime, abbreviated by -t
#SBATCH --ntasks=%(np)d   # number of MPI tasks, abbreviated by -n
#SBATCH --nodes=%(nodes)d     # number of cluster nodes, abbreviated by -N
#SBATCH --nodelist=ember-gg[01-12] # only use GG nodes
#SBATCH --job-name=WRFX  # job name

# set data and working directories
export WORKDIR=%(cwd)s 
cd $WORKDIR

source ~/.wrf_arm

# Clean old OpenMPI MCA settings
unset OMPI_MCA_btl_openib_allow_ib
unset OMPI_MCA_btl_openib_warn_no_device_params_found
unset OMPI_MCA_btl_tcp_if_exclude
unset OMPI_MCA_btl_tcp_if_include
unset OMPI_MCA_oob_tcp_if_exclude
unset OMPI_MCA_oob_tcp_if_include
# Force UCX PML
export OMPI_MCA_pml=ucx
export OMPI_MCA_osc=ucx
# Explicitly disable legacy openib BTL
export OMPI_MCA_btl="^openib"
# Keep OpenMPI out-of-band control traffic on InfiniBand interface
export OMPI_MCA_oob_tcp_if_include=ib0
# If TCP BTL is ever used, restrict it to ib0.
export OMPI_MCA_btl_tcp_if_include=ib0
# UCX: restrict data path to real InfiniBand devices
export UCX_NET_DEVICES=mlx5_2:1,mlx5_3:1
export UCX_TLS=rc,sm,self
export UCX_IB_GID_INDEX=0
# Debugging with warnings
export UCX_LOG_LEVEL=warn
export OMPI_MCA_orte_base_help_aggregate=1

time mpirun -n $SLURM_NTASKS ./wrf.exe
