#Functionality for storing and retrieving the system state, saving maps, etc
import glob
import time
import os
import pandas as pd
import numpy as np
from mpl_toolkits.basemap import Basemap
#from ngfs import config_manager
import matplotlib.pyplot as plt
from PIL import Image
from datetime import timedelta, datetime

####### Functions  #######
def get_old_incidents(ngfs_directory):
    """
    Looks at older, saved ngfs_days objects and finds incidents that have already been processed or forecasted.
    """
    from ngfs.ngfs_day import ngfs_day
    print('Reading previous pickle file(s)')
    
    # Get and sort pickle files by modification time
    full_pick_list = sorted(glob.glob(f'{ngfs_directory}/*.pkl'), key=os.path.getmtime)
    current_time = time.time()

    # Filter out old pickle files not generated by specific CSV files
    pick_list = [
        i for i in full_pick_list
        if 'GOES' not in i and (current_time - os.path.getmtime(i)) / 3600 < 24 * 7
    ]

    #take most recent pickle file, even if it is older than 7 days
    if not len(pick_list):
      pick_list = [full_pick_list[-1]] #make sure its a list
      print(pick_list)

    print(f'Number of pickle files to possibly look at: {len(pick_list)}')
    
    # Reverse the list to get the newest files first
    pick_list.reverse()
    
    old_ngfs_incidents = []
    started_inc_ids = []

    for i in pick_list:
        print(f'\tReading {i}')
        df = pd.read_pickle(i)
        old_ngfs_incidents.extend(df.incidents)

        if hasattr(df, 'started_inc_ids'):
            started_inc_ids.extend(df.started_inc_ids)
            print(f'\tTracking {len(started_inc_ids)} old incident ID strings')
            break
        else:
            print('\tPickle file does not have started_inc_ids')
        print(len(started_inc_ids))

    print(f'\tTimestamp of of loaded ngfs_day object: {df.timestamp} with data size: {len(df.data)}')
    # Process and print old incidents
    print('Found the previous incidents:')
    for inc in old_ngfs_incidents:
        if inc.incident_id_string in started_inc_ids or inc.started:
            inc.started = True
            if inc.incident_id_string not in started_inc_ids:
                started_inc_ids.append(inc.incident_id_string)
        print(f'\t{inc.incident_id_string} {inc.incident_name} Started = {inc.started}')
    
    
    return list(set(started_inc_ids)), old_ngfs_incidents, df

def detection_summary(ngfs_day, hours=24):
    """
    Print summary information about detections from the various sources
    over the previous period of length `hours`.
    """
    print(f'Length of dat set: {len(ngfs_day.data)}')
    min_time = ngfs_day.timestamp - timedelta(hours=hours)
    # Determine time column
    for c in ngfs_day.data.columns:
        if 'time' in c:
            time_col = c
    # Filter once
    df = ngfs_day.data# [ngfs_day.data[time_col] > min_time].copy()
    sat_list = list(df.satellite.unique())
    det_summary = pd.DataFrame()
    for sat in sat_list:
        tmp = dict()
        print(sat)
        data = df[df.satellite == sat ].copy()
        print(f'Length of {sat} data set: {len(data)}')
        tmp['satellite_name'] = sat
        tmp['start_timestamp'] = data[time_col].min()
        tmp['end_timestamp'] = ngfs_day.timestamp
        tmp['known_incidents'] = len(data.known_incident_id.unique())
        tmp['total_detections'] = len(data)
        if "type_description" in data.columns:
            tmp['known_wildland_fire'] = len(data[data.type_description == 'Known Wildland Fire Incident'])
            tmp['possible_wildland_fire'] = len(data[data.type_description == 'Possible Wildland Fire'])
        else:
            tmp['known_wildland_fire'] = len(data[data.type == 1])
            tmp['possible_wildland_fire'] = len(data[data.type == 0])
        tmp['total_frp'] = np.sum(data.frp)
        for k in tmp.keys():
            print(f'\t{k}\t{tmp[k]}')
        #
        det_summary = det_summary.append(pd.DataFrame(tmp,index=[tmp['satellite_name']]))
    # Save
    det_summary.to_csv("ngfs/detection_summary_testing.csv", index=False)
    det_summary.to_csv(f"ngfs/detection_summary_{ngfs_day.date_str}_testing.csv", index=False)
    #return det_summary
def print_base_map(ngfs_day):
    #prints map of locations of incidents within ngfs_day object
    print('Starting map making')
    #find, new, started, and ongoing incidents
    ngfs_day.set_new()
    ngfs_day.set_started()
    ngfs_day.set_ongoing()

    #projects coordinates onto the map space
    def get_coords(latlons, mask, map):
        #map is a Basemap object, this returns projected coordinates
        #mask is boolean array
        filtered = latlons[mask]
        return map(filtered[:, 1], filtered[:, 0])
    #scatters locations onto map
    def scatter_if_any(x, y, size, label, map):
        #scatters projected coordinates and adds legend text to plot
        if len(x) > 0:
            map.scatter(x, y, s=size, label=label, edgecolors='black')
    #CONUS map
    m = Basemap(llcrnrlon=-119, llcrnrlat=22, urcrnrlon=-64, urcrnrlat=49, projection='lcc', lat_1=33, lat_2=45, lon_0=-95)
    m.latlon = True
    m.shadedrelief()
    m.drawstates()
    m.drawcountries()
    m.drawcoastlines()

    #nx2 matrix with lat,lon as columns
    latlons = ngfs_day.incident_ign_latlons()
    #print('latlons',latlons)

    #tuple with incident status, icon size, legend text label for plotting on map
    incident_data = [
        (ngfs_day.ongoing, 15, 'Ongoing Incident'),
        (np.logical_and(~ngfs_day.started,ngfs_day.new), 30, 'New Incident'),
        (np.logical_and(ngfs_day.started,ngfs_day.new), 30, 'New, Forecast Started')
    ]

    #scatter the CONUS incidents
    for data, size, label in incident_data:
        #data is a boolean array
        x, y = get_coords(latlons, data, m)
        scatter_if_any(x, y, size, label, m)

    plt.legend(loc="lower left")
    plt.title(f'NIFC Fire Incidents \n{ngfs_day.date_str}\n {ngfs_day.sat_name}')

    print('Saving ', ngfs_day.map_save_str)
    plt.savefig(ngfs_day.map_save_str, bbox_inches='tight')  #always saved
    plt.cla()

    #if there are fires in Alaska, make a map and join it to the existing CONUS map
    if max(latlons[:, 0]) > 54.0:
        n = Basemap(llcrnrlon=-164, llcrnrlat=54, urcrnrlon=-130, urcrnrlat=73, projection='lcc', lat_1=63, lat_2=68, lon_0=-151)
        n.latlon = True
        n.shadedrelief()
        n.drawstates()
        n.drawcountries()
        n.drawcoastlines()
        #scatter the Alaska incidents on Alaskan map
        for data, size, label in incident_data:
            x, y = get_coords(latlons, data, n)
            scatter_if_any(x, y, size, label, n)

        plt.legend(loc="lower right")
        plt.title(f'NIFC Alaska Fire Incidents \n{ngfs_day.date_str}\n GOES-18')

        sv_str = ngfs_day.map_save_str.replace('ngfs/', 'ngfs/Alaska_')
        print('Saving ', sv_str)
        plt.savefig(sv_str, bbox_inches='tight')

        conus_str = ngfs_day.map_save_str.replace('ngfs/', 'ngfs/CONUS_')
        os.system(f'cp {ngfs_day.map_save_str} {conus_str}')

        #join alaska and CONUS image after waiting for file to write
        time.sleep(20)
        img0 = Image.open(ngfs_day.map_save_str)
        img1 = Image.open(sv_str)

        height = img0.size[1]
        width = int(np.round(height * img1.size[0] / img1.size[1]))
        img1 = img1.resize((width, height), Image.LANCZOS)
        img1.save(sv_str)

        image_new = Image.new("RGB", (img0.size[0] + img1.size[0], height), "white")
        image_new.paste(img1, (0, 0))
        image_new.paste(img0, (width, 0))
        image_new.save(ngfs_day.map_save_str)

def save_incident_text(ngfs_day):
      """
      Saves the estimated ignition point information for all new incidents as a CSV file.
      """
      #Needs to add
      # additional fields to the csv file such as viirs pixel location and assumed ignition time
      # use pd.to_csv() function
      ign_pix = pd.DataFrame()
      new_ign_lat = []
      new_ign_lon = []
      new_ign_time = []
      viirs_pixel = []

      for inc in ngfs_day.incidents:
         #print(inc.name,inc.new)
         if (inc.new & inc.started):
            #print(inc.ignition_pixel)
            ign_pix = ign_pix.append(inc.ignition_pixel)
            #for adding columns to the csv
            try:
               new_ign_lat = np.append(new_ign_lat,inc.new_ign_latlon[0])
               new_ign_lon = np.append(new_ign_lon,inc.new_ign_latlon[1])
               new_ign_time.append(inc.ign_utc)
               viirs_pix = True
               #viirs_pixel.append(True)
            except AttributeError:
               new_ign_lat = np.append(new_ign_lat,inc.ign_latlon[0])
               new_ign_lon = np.append(new_ign_lon,inc.ign_latlon[1])
               new_ign_time.append(inc.ign_utc)
               viirs_pix = False
            if hasattr(inc,'viirs_ignition_pixel'):
               viirs_pixel.append(inc.viirs_ignition_pixel)
            else:
               viirs_pixel.append(viirs_pix)
            
      #print('length of new vars',len(new_ign_lat),len(new_ign_lon),len(new_ign_time))
      #print('dataframe shape',ign_pix.shape)
      ign_pix['forecast_ign_lat'] = new_ign_lat
      ign_pix['forecast_ign_lon'] = new_ign_lon
      ign_pix['forecast_ign_UTC'] = new_ign_time
      ign_pix['viirs_pixel_ign'] = viirs_pixel
      print(ign_pix)
      #only save non-empty dataframe
      if not ign_pix.empty:
         time_str = time.strftime("%H_%M", time.localtime())
         csv_save_str = f'ngfs/forecast_ignition_pixels_{ngfs_day.date_str}_{time_str}.csv'
         ign_pix.to_csv(csv_save_str, index=False)

if __name__ == '__main__':
    pass
